#!/bin/sh

# source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc

# if not running interactively, don't do anything
[[ -z "$PS1" ]] && return

# control history
shopt -s histappend
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=1000
HISTFILESIZE=2000

# number of threads to use for Intel MKL
export MKL_NUM_THREADS=1

# aliases
unalias -a
alias ls='ls -Gp'
alias ll='ls -aFhl'
alias g='git'
alias psa='ps aux'
alias pingg='ping -c 3 www.google.com'
alias be='bundle exec'
alias bitcoin='curl -s https://bitpay.com/api/rates | jq .[2]'

# function to pull master and then go back to your current branch
function pullmaster {
  current=$(git symbolic-ref HEAD 2> /dev/null) || return
  git checkout master && git pull && git checkout ${current#refs/heads/}
}

# function to get current branch if PWD is a git repo
function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}

# command line prompt
if [ $(tput colors) -ge 8 ]; then
  BLACK="\[\033[0;30m\]"
  RED="\[\033[0;31m\]"
  GREEN="\[\033[0;32m\]"
  YELLOW="\[\033[0;33m\]"
  BLUE="\[\033[0;34m\]"
  MAGENTA="\[\033[0;35m\]"
  CYAN="\[\033[0;36m\]"
  WHITE="\[\033[0;37m\]"
  NORMAL="\[\033[0;0m\]"
  export PS1="$RED\u@\h $BLUE\W $YELLOW\$(parse_git_branch)$NORMAL\n\\$ "
else
  export PS1="\u@\h \W $(parse_git_branch)\n\\$ "
fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# ensure /usr/local/bin is always before /usr/bin
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# pyenv (https://github.com/yyuu/pyenv)
export PATH=$HOME/.pyenv/bin:$PATH
eval "$(pyenv init -)"
pyenv global 2.7.5

# virtualenvwrapper
source "${HOME}/.pyenv/versions/2.7.5/bin/virtualenvwrapper.sh"

# minimise pip downloads
export PIP_DOWNLOAD_CACHE="${HOME}/.pip/cache"
[[ ! -d $PIP_DOWNLOAD_CACHE ]] && mkdir -p $PIP_DOWNLOAD_CACHE

# rbenv (https://github.com/sstephenson/rbenv)
export PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH
eval "$(rbenv init -)"
rbenv global 2.1.4

# Postgres.app
[[ -d /Applications/Postgres.app ]] && export PATH=/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH

# the one true editor
export EDITOR=emacs

# project directory (used by virtualenvs)
export PROJECT_DIR="${HOME}/Projects"

# git-hooks (https://github.com/icefox/git-hooks)
[[ -d ${PROJECT_DIR}/git-hooks ]] && export PATH=${PATH}:${PROJECT_DIR}/git-hooks

# aliases to control MySQL server
if [ -x $(which mysql.server) ]; then
  alias mysqlup='mysql.server start'
  alias mysqldown='mysql.server stop'
fi

# added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# added by travis gem
[ -f /Users/murtaza/.travis/travis.sh ] && source /Users/murtaza/.travis/travis.sh

# add personal bin directory (this should always be at the end)
[[ -d ${HOME}/bin ]] && export PATH=${HOME}/bin:${PATH}
