#!/bin/zsh

## History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

## History command configuration
setopt EXTENDED_HISTORY       # record timestamp of command in HISTFILE
setopt HIST_EXPIRE_DUPS_FIRST # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt HIST_FIND_NO_DUPS      # ignore duplicated commands when searching
setopt HIST_IGNORE_DUPS       # ignore duplicated commands history list
setopt HIST_IGNORE_SPACE      # ignore commands that start with space
setopt HIST_REDUCE_BLANKS     # remove blank lines from history
setopt HIST_VERIFY            # show command with history expansion to user before running it
setopt INC_APPEND_HISTORY     # add commands to HISTFILE in order of execution
setopt SHARE_HISTORY          # share command history data

## Number of threads to use for Intel MKL
export MKL_NUM_THREADS=1

## The One True Editor
export EDITOR=emacs

## Locale settings
export LC_ALL=$LANG

## Aliases
unalias -a
alias be='bundle exec'
alias e='emacs'
alias g='git'
alias k='kubectl'
alias ll='ls -aFhl'
alias ls='ls -Gp'
alias pingg='ping -c 3 www.google.com'
alias pr='pipenv run'
alias psa='ps aux'
alias ssm='aws ssm start-session --target'

## Homebrew
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi
export PATH="/usr/local/sbin:$PATH"

## Git configuration
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' formats '%F{yellow}(%b)%f'
zstyle ':vcs_info:*' enable git

## Command line prompt
NEWLINE=$'\n'
PROMPT="%F{green}%*%f %F{blue}%1~%f \$vcs_info_msg_0_${NEWLINE}%(!.#.->) "

## Project directory
export PROJECT_HOME="$HOME/Projects"

## Add personal bin directories to PATH
[[ -d "$HOME/.local/bin" ]] && export PATH="$HOME/.local/bin:$PATH"
[[ -d "$PROJECT_HOME/bin" ]] && export PATH="$PROJECT_HOME/bin:$PATH"

## GPG uses current terminal to sign commits
export GPG_TTY=$(tty)

## asdf (https://asdf-vm.com/)
if [ -d "$HOME/.asdf" ]; then
  export PATH="$HOME/.asdf/shims:$PATH"
  fpath=("$HOME/.asdf/completions" $fpath)
  autoload -Uz compinit && compinit
fi

## virtualenvwrapper
export WORKON_HOME="$HOME/.virtualenvs"
. "$(asdf where python)/bin/virtualenvwrapper.sh"

## direnv
eval "$(direnv hook zsh)"

# bun
if [ -s "$HOME/.bun/_bun" ]; then
  . "$HOME/.bun/_bun"

  export BUN_INSTALL="$HOME/.bun"
  export PATH="$BUN_INSTALL/bin:$PATH"
fi

# Java
. "$HOME/.asdf/plugins/java/set-java-home.zsh"

# Android
export ANDROID_HOME=$HOME/Library/Android/sdk
if [ -d "$ANDROID_HOME" ]; then
  export PATH="$PATH:$ANDROID_HOME/emulator"
  export PATH="$PATH:$ANDROID_HOME/platform-tools"
fi

## Volta
# export VOLTA_HOME="$HOME/.volta"
# export PATH="$VOLTA_HOME/bin:$PATH"
