#!/bin/bash
# This hook is sourced after this virtualenv is activated.

PS1="(`basename \"$VIRTUAL_ENV\"`) $_OLD_VIRTUAL_PS1"
export OLD_PYTHONPATH=$PYTHONPATH

cd $PROJECT_DIR/`basename $VIRTUAL_ENV` && export PYTHONPATH=$PWD:$OLD_PYTHONPATH
[[ -f development.env ]] && source development.env
