#!/bin/bash
# This hook is run after every virtualenv is activated.

PS1="(`basename \"$VIRTUAL_ENV\"`) $_OLD_VIRTUAL_PS1"

cd $PROJECT_DIR/`basename $VIRTUAL_ENV`
[[ -f development.env ]] && source development.env
